version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: "server"
    goos:
      - linux
      - darwin
    main: ./cmd/server
    binary: ticketbot

  - id: admin-cli
    goos:
      - linux
      - darwin
    main: ./cmd/tbot-admin
    binary: tbot-admin

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
