// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: addigy_alert.sql

package db

import (
	"context"
)

const deleteAddigyAlertConfig = `-- name: DeleteAddigyAlertConfig :exec
DELETE FROM addigy_alert_config
WHERE id = 1
`

func (q *Queries) DeleteAddigyAlertConfig(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAddigyAlertConfig)
	return err
}

const getAddigyAlertConfig = `-- name: GetAddigyAlertConfig :one
SELECT id, cw_board_id, unattended_status_id, acknowledged_status_id, mute_1_day_status_id, mute_5_day_status_id, mute_10_day_status_id, mute_30_day_status_id, added_on, updated_on FROM addigy_alert_config
WHERE id = 1
`

func (q *Queries) GetAddigyAlertConfig(ctx context.Context) (*AddigyAlertConfig, error) {
	row := q.db.QueryRow(ctx, getAddigyAlertConfig)
	var i AddigyAlertConfig
	err := row.Scan(
		&i.ID,
		&i.CwBoardID,
		&i.UnattendedStatusID,
		&i.AcknowledgedStatusID,
		&i.Mute1DayStatusID,
		&i.Mute5DayStatusID,
		&i.Mute10DayStatusID,
		&i.Mute30DayStatusID,
		&i.AddedOn,
		&i.UpdatedOn,
	)
	return &i, err
}

const upsertAddigyAlertConfig = `-- name: UpsertAddigyAlertConfig :one
INSERT INTO addigy_alert_config (
    id,
    cw_board_id,
    unattended_status_id,
    acknowledged_status_id,
    mute_1_day_status_id,
    mute_5_day_status_id,
    mute_10_day_status_id,
    mute_30_day_status_id
) 
VALUES (1, $1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO UPDATE SET
    cw_board_id = EXCLUDED.cw_board_id,
    unattended_status_id = EXCLUDED.unattended_status_id,
    acknowledged_status_id = EXCLUDED.acknowledged_status_id,
    mute_1_day_status_id = EXCLUDED.mute_1_day_status_id,
    mute_5_day_status_id = EXCLUDED.mute_5_day_status_id,
    mute_10_day_status_id = EXCLUDED.mute_10_day_status_id,
    mute_30_day_status_id = EXCLUDED.mute_30_day_status_id,
    updated_on = NOW()
RETURNING id, cw_board_id, unattended_status_id, acknowledged_status_id, mute_1_day_status_id, mute_5_day_status_id, mute_10_day_status_id, mute_30_day_status_id, added_on, updated_on
`

type UpsertAddigyAlertConfigParams struct {
	CwBoardID            int `json:"cw_board_id"`
	UnattendedStatusID   int `json:"unattended_status_id"`
	AcknowledgedStatusID int `json:"acknowledged_status_id"`
	Mute1DayStatusID     int `json:"mute_1_day_status_id"`
	Mute5DayStatusID     int `json:"mute_5_day_status_id"`
	Mute10DayStatusID    int `json:"mute_10_day_status_id"`
	Mute30DayStatusID    int `json:"mute_30_day_status_id"`
}

func (q *Queries) UpsertAddigyAlertConfig(ctx context.Context, arg UpsertAddigyAlertConfigParams) (*AddigyAlertConfig, error) {
	row := q.db.QueryRow(ctx, upsertAddigyAlertConfig,
		arg.CwBoardID,
		arg.UnattendedStatusID,
		arg.AcknowledgedStatusID,
		arg.Mute1DayStatusID,
		arg.Mute5DayStatusID,
		arg.Mute10DayStatusID,
		arg.Mute30DayStatusID,
	)
	var i AddigyAlertConfig
	err := row.Scan(
		&i.ID,
		&i.CwBoardID,
		&i.UnattendedStatusID,
		&i.AcknowledgedStatusID,
		&i.Mute1DayStatusID,
		&i.Mute5DayStatusID,
		&i.Mute10DayStatusID,
		&i.Mute30DayStatusID,
		&i.AddedOn,
		&i.UpdatedOn,
	)
	return &i, err
}
