// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cw_ticket.sql

package db

import (
	"context"
)

const deleteTicket = `-- name: DeleteTicket :exec
DELETE FROM cw_ticket
WHERE id = $1
`

func (q *Queries) DeleteTicket(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteTicket, id)
	return err
}

const deleteTicketNote = `-- name: DeleteTicketNote :exec
DELETE FROM cw_ticket_note
WHERE id = $1
`

func (q *Queries) DeleteTicketNote(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteTicketNote, id)
	return err
}

const getTicket = `-- name: GetTicket :one
SELECT id, summary, board_id, owner_id, company_id, contact_id, resources, updated_by, updated_on, added_on, deleted FROM cw_ticket
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTicket(ctx context.Context, id int) (CwTicket, error) {
	row := q.db.QueryRow(ctx, getTicket, id)
	var i CwTicket
	err := row.Scan(
		&i.ID,
		&i.Summary,
		&i.BoardID,
		&i.OwnerID,
		&i.CompanyID,
		&i.ContactID,
		&i.Resources,
		&i.UpdatedBy,
		&i.UpdatedOn,
		&i.AddedOn,
		&i.Deleted,
	)
	return i, err
}

const getTicketNote = `-- name: GetTicketNote :one
SELECT id, ticket_id, member_id, contact_id, notified, skipped_notify, updated_on, added_on, deleted FROM cw_ticket_note
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTicketNote(ctx context.Context, id int) (CwTicketNote, error) {
	row := q.db.QueryRow(ctx, getTicketNote, id)
	var i CwTicketNote
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.MemberID,
		&i.ContactID,
		&i.Notified,
		&i.SkippedNotify,
		&i.UpdatedOn,
		&i.AddedOn,
		&i.Deleted,
	)
	return i, err
}

const insertTicket = `-- name: InsertTicket :one
INSERT INTO cw_ticket
(id, summary, board_id, owner_id, company_id, contact_id, resources, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, summary, board_id, owner_id, company_id, contact_id, resources, updated_by, updated_on, added_on, deleted
`

type InsertTicketParams struct {
	ID        int     `json:"id"`
	Summary   string  `json:"summary"`
	BoardID   int     `json:"board_id"`
	OwnerID   *int    `json:"owner_id"`
	CompanyID int     `json:"company_id"`
	ContactID *int    `json:"contact_id"`
	Resources *string `json:"resources"`
	UpdatedBy *string `json:"updated_by"`
}

func (q *Queries) InsertTicket(ctx context.Context, arg InsertTicketParams) (CwTicket, error) {
	row := q.db.QueryRow(ctx, insertTicket,
		arg.ID,
		arg.Summary,
		arg.BoardID,
		arg.OwnerID,
		arg.CompanyID,
		arg.ContactID,
		arg.Resources,
		arg.UpdatedBy,
	)
	var i CwTicket
	err := row.Scan(
		&i.ID,
		&i.Summary,
		&i.BoardID,
		&i.OwnerID,
		&i.CompanyID,
		&i.ContactID,
		&i.Resources,
		&i.UpdatedBy,
		&i.UpdatedOn,
		&i.AddedOn,
		&i.Deleted,
	)
	return i, err
}

const insertTicketNote = `-- name: InsertTicketNote :one
INSERT INTO cw_ticket_note
(id, ticket_id, member_id, contact_id, notified, skipped_notify)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, ticket_id, member_id, contact_id, notified, skipped_notify, updated_on, added_on, deleted
`

type InsertTicketNoteParams struct {
	ID            int  `json:"id"`
	TicketID      int  `json:"ticket_id"`
	MemberID      *int `json:"member_id"`
	ContactID     *int `json:"contact_id"`
	Notified      bool `json:"notified"`
	SkippedNotify bool `json:"skipped_notify"`
}

func (q *Queries) InsertTicketNote(ctx context.Context, arg InsertTicketNoteParams) (CwTicketNote, error) {
	row := q.db.QueryRow(ctx, insertTicketNote,
		arg.ID,
		arg.TicketID,
		arg.MemberID,
		arg.ContactID,
		arg.Notified,
		arg.SkippedNotify,
	)
	var i CwTicketNote
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.MemberID,
		&i.ContactID,
		&i.Notified,
		&i.SkippedNotify,
		&i.UpdatedOn,
		&i.AddedOn,
		&i.Deleted,
	)
	return i, err
}

const listAllTicketNotes = `-- name: ListAllTicketNotes :many
SELECT id, ticket_id, member_id, contact_id, notified, skipped_notify, updated_on, added_on, deleted FROM cw_ticket_note
ORDER BY id
`

func (q *Queries) ListAllTicketNotes(ctx context.Context) ([]CwTicketNote, error) {
	rows, err := q.db.Query(ctx, listAllTicketNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CwTicketNote
	for rows.Next() {
		var i CwTicketNote
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.MemberID,
			&i.ContactID,
			&i.Notified,
			&i.SkippedNotify,
			&i.UpdatedOn,
			&i.AddedOn,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketNotesByTicket = `-- name: ListTicketNotesByTicket :many
SELECT id, ticket_id, member_id, contact_id, notified, skipped_notify, updated_on, added_on, deleted FROM cw_ticket_note
WHERE ticket_id = $1
ORDER BY id
`

func (q *Queries) ListTicketNotesByTicket(ctx context.Context, ticketID int) ([]CwTicketNote, error) {
	rows, err := q.db.Query(ctx, listTicketNotesByTicket, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CwTicketNote
	for rows.Next() {
		var i CwTicketNote
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.MemberID,
			&i.ContactID,
			&i.Notified,
			&i.SkippedNotify,
			&i.UpdatedOn,
			&i.AddedOn,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTickets = `-- name: ListTickets :many
SELECT id, summary, board_id, owner_id, company_id, contact_id, resources, updated_by, updated_on, added_on, deleted FROM cw_ticket
ORDER BY id
`

func (q *Queries) ListTickets(ctx context.Context) ([]CwTicket, error) {
	rows, err := q.db.Query(ctx, listTickets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CwTicket
	for rows.Next() {
		var i CwTicket
		if err := rows.Scan(
			&i.ID,
			&i.Summary,
			&i.BoardID,
			&i.OwnerID,
			&i.CompanyID,
			&i.ContactID,
			&i.Resources,
			&i.UpdatedBy,
			&i.UpdatedOn,
			&i.AddedOn,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNoteNotified = `-- name: SetNoteNotified :one
UPDATE cw_ticket_note
SET
    notified = $2
WHERE id = $1
RETURNING id, ticket_id, member_id, contact_id, notified, skipped_notify, updated_on, added_on, deleted
`

type SetNoteNotifiedParams struct {
	ID       int  `json:"id"`
	Notified bool `json:"notified"`
}

func (q *Queries) SetNoteNotified(ctx context.Context, arg SetNoteNotifiedParams) (CwTicketNote, error) {
	row := q.db.QueryRow(ctx, setNoteNotified, arg.ID, arg.Notified)
	var i CwTicketNote
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.MemberID,
		&i.ContactID,
		&i.Notified,
		&i.SkippedNotify,
		&i.UpdatedOn,
		&i.AddedOn,
		&i.Deleted,
	)
	return i, err
}

const setNoteSkippedNotify = `-- name: SetNoteSkippedNotify :one
UPDATE cw_ticket_note
SET
    skipped_notify = $2
WHERE id = $1
RETURNING id, ticket_id, member_id, contact_id, notified, skipped_notify, updated_on, added_on, deleted
`

type SetNoteSkippedNotifyParams struct {
	ID            int  `json:"id"`
	SkippedNotify bool `json:"skipped_notify"`
}

func (q *Queries) SetNoteSkippedNotify(ctx context.Context, arg SetNoteSkippedNotifyParams) (CwTicketNote, error) {
	row := q.db.QueryRow(ctx, setNoteSkippedNotify, arg.ID, arg.SkippedNotify)
	var i CwTicketNote
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.MemberID,
		&i.ContactID,
		&i.Notified,
		&i.SkippedNotify,
		&i.UpdatedOn,
		&i.AddedOn,
		&i.Deleted,
	)
	return i, err
}

const softDeleteTicket = `-- name: SoftDeleteTicket :exec
UPDATE cw_ticket
SET
    deleted = TRUE,
    updated_on = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteTicket(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, softDeleteTicket, id)
	return err
}

const softDeleteTicketNote = `-- name: SoftDeleteTicketNote :exec
UPDATE cw_ticket_note
SET deleted = TRUE
WHERE id = $1
`

func (q *Queries) SoftDeleteTicketNote(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, softDeleteTicketNote, id)
	return err
}

const updateTicket = `-- name: UpdateTicket :one
UPDATE cw_ticket
SET
    summary = $2,
    board_id = $3,
    owner_id = $4,
    company_id = $5,
    contact_id = $6,
    resources = $7,
    updated_by = $8,
    updated_on = NOW()
WHERE id = $1
RETURNING id, summary, board_id, owner_id, company_id, contact_id, resources, updated_by, updated_on, added_on, deleted
`

type UpdateTicketParams struct {
	ID        int     `json:"id"`
	Summary   string  `json:"summary"`
	BoardID   int     `json:"board_id"`
	OwnerID   *int    `json:"owner_id"`
	CompanyID int     `json:"company_id"`
	ContactID *int    `json:"contact_id"`
	Resources *string `json:"resources"`
	UpdatedBy *string `json:"updated_by"`
}

func (q *Queries) UpdateTicket(ctx context.Context, arg UpdateTicketParams) (CwTicket, error) {
	row := q.db.QueryRow(ctx, updateTicket,
		arg.ID,
		arg.Summary,
		arg.BoardID,
		arg.OwnerID,
		arg.CompanyID,
		arg.ContactID,
		arg.Resources,
		arg.UpdatedBy,
	)
	var i CwTicket
	err := row.Scan(
		&i.ID,
		&i.Summary,
		&i.BoardID,
		&i.OwnerID,
		&i.CompanyID,
		&i.ContactID,
		&i.Resources,
		&i.UpdatedBy,
		&i.UpdatedOn,
		&i.AddedOn,
		&i.Deleted,
	)
	return i, err
}

const updateTicketNote = `-- name: UpdateTicketNote :one
UPDATE cw_ticket_note
SET
    ticket_id = $2,
    member_id = $3,
    contact_id = $4,
    notified = $5,
    skipped_notify = $6,
    updated_on = NOW()
WHERE id = $1
RETURNING id, ticket_id, member_id, contact_id, notified, skipped_notify, updated_on, added_on, deleted
`

type UpdateTicketNoteParams struct {
	ID            int  `json:"id"`
	TicketID      int  `json:"ticket_id"`
	MemberID      *int `json:"member_id"`
	ContactID     *int `json:"contact_id"`
	Notified      bool `json:"notified"`
	SkippedNotify bool `json:"skipped_notify"`
}

func (q *Queries) UpdateTicketNote(ctx context.Context, arg UpdateTicketNoteParams) (CwTicketNote, error) {
	row := q.db.QueryRow(ctx, updateTicketNote,
		arg.ID,
		arg.TicketID,
		arg.MemberID,
		arg.ContactID,
		arg.Notified,
		arg.SkippedNotify,
	)
	var i CwTicketNote
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.MemberID,
		&i.ContactID,
		&i.Notified,
		&i.SkippedNotify,
		&i.UpdatedOn,
		&i.AddedOn,
		&i.Deleted,
	)
	return i, err
}
