// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifier_connection.sql

package db

import (
	"context"
)

const checkNotifierExists = `-- name: CheckNotifierExists :one
SELECT EXISTS (
    SELECT 1
    FROM notifier_connection
    WHERE cw_board_id = $1 AND webex_room_id = $2
) AS exists
`

type CheckNotifierExistsParams struct {
	CwBoardID   int `json:"cw_board_id"`
	WebexRoomID int `json:"webex_room_id"`
}

func (q *Queries) CheckNotifierExists(ctx context.Context, arg CheckNotifierExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkNotifierExists, arg.CwBoardID, arg.WebexRoomID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteNotifierConnection = `-- name: DeleteNotifierConnection :exec
DELETE FROM notifier_connection
WHERE id = $1
`

func (q *Queries) DeleteNotifierConnection(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteNotifierConnection, id)
	return err
}

const getNotifierConnection = `-- name: GetNotifierConnection :one
SELECT id, cw_board_id, webex_room_id, notify_enabled, created_on FROM notifier_connection
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetNotifierConnection(ctx context.Context, id int) (NotifierConnection, error) {
	row := q.db.QueryRow(ctx, getNotifierConnection, id)
	var i NotifierConnection
	err := row.Scan(
		&i.ID,
		&i.CwBoardID,
		&i.WebexRoomID,
		&i.NotifyEnabled,
		&i.CreatedOn,
	)
	return i, err
}

const insertNotifierConnection = `-- name: InsertNotifierConnection :one
INSERT INTO notifier_connection(cw_board_id, webex_room_id, notify_enabled)
VALUES ($1, $2, $3)
RETURNING id, cw_board_id, webex_room_id, notify_enabled, created_on
`

type InsertNotifierConnectionParams struct {
	CwBoardID     int  `json:"cw_board_id"`
	WebexRoomID   int  `json:"webex_room_id"`
	NotifyEnabled bool `json:"notify_enabled"`
}

func (q *Queries) InsertNotifierConnection(ctx context.Context, arg InsertNotifierConnectionParams) (NotifierConnection, error) {
	row := q.db.QueryRow(ctx, insertNotifierConnection, arg.CwBoardID, arg.WebexRoomID, arg.NotifyEnabled)
	var i NotifierConnection
	err := row.Scan(
		&i.ID,
		&i.CwBoardID,
		&i.WebexRoomID,
		&i.NotifyEnabled,
		&i.CreatedOn,
	)
	return i, err
}

const listNotifierConnections = `-- name: ListNotifierConnections :many
SELECT id, cw_board_id, webex_room_id, notify_enabled, created_on FROM notifier_connection
ORDER BY id
`

func (q *Queries) ListNotifierConnections(ctx context.Context) ([]NotifierConnection, error) {
	rows, err := q.db.Query(ctx, listNotifierConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotifierConnection
	for rows.Next() {
		var i NotifierConnection
		if err := rows.Scan(
			&i.ID,
			&i.CwBoardID,
			&i.WebexRoomID,
			&i.NotifyEnabled,
			&i.CreatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifierConnectionsByBoard = `-- name: ListNotifierConnectionsByBoard :many
SELECT id, cw_board_id, webex_room_id, notify_enabled, created_on FROM notifier_connection
WHERE cw_board_id = $1
ORDER BY id
`

func (q *Queries) ListNotifierConnectionsByBoard(ctx context.Context, cwBoardID int) ([]NotifierConnection, error) {
	rows, err := q.db.Query(ctx, listNotifierConnectionsByBoard, cwBoardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotifierConnection
	for rows.Next() {
		var i NotifierConnection
		if err := rows.Scan(
			&i.ID,
			&i.CwBoardID,
			&i.WebexRoomID,
			&i.NotifyEnabled,
			&i.CreatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifierConnectionsByRoom = `-- name: ListNotifierConnectionsByRoom :many
SELECT id, cw_board_id, webex_room_id, notify_enabled, created_on FROM notifier_connection
WHERE webex_room_id = $1
ORDER BY id
`

func (q *Queries) ListNotifierConnectionsByRoom(ctx context.Context, webexRoomID int) ([]NotifierConnection, error) {
	rows, err := q.db.Query(ctx, listNotifierConnectionsByRoom, webexRoomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotifierConnection
	for rows.Next() {
		var i NotifierConnection
		if err := rows.Scan(
			&i.ID,
			&i.CwBoardID,
			&i.WebexRoomID,
			&i.NotifyEnabled,
			&i.CreatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteNotifierConnection = `-- name: SoftDeleteNotifierConnection :exec
UPDATE notifier_connection
SET
    deleted = TRUE,
    updated_on = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteNotifierConnection(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, softDeleteNotifierConnection, id)
	return err
}

const updateNotifierConnection = `-- name: UpdateNotifierConnection :one
UPDATE notifier_connection
SET
    cw_board_id = $2,
    webex_room_id = $3,
    notify_enabled = $4
WHERE id = $1
RETURNING id, cw_board_id, webex_room_id, notify_enabled, created_on
`

type UpdateNotifierConnectionParams struct {
	ID            int  `json:"id"`
	CwBoardID     int  `json:"cw_board_id"`
	WebexRoomID   int  `json:"webex_room_id"`
	NotifyEnabled bool `json:"notify_enabled"`
}

func (q *Queries) UpdateNotifierConnection(ctx context.Context, arg UpdateNotifierConnectionParams) (NotifierConnection, error) {
	row := q.db.QueryRow(ctx, updateNotifierConnection,
		arg.ID,
		arg.CwBoardID,
		arg.WebexRoomID,
		arg.NotifyEnabled,
	)
	var i NotifierConnection
	err := row.Scan(
		&i.ID,
		&i.CwBoardID,
		&i.WebexRoomID,
		&i.NotifyEnabled,
		&i.CreatedOn,
	)
	return i, err
}
