// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifier_connection.sql

package db

import (
	"context"
)

const deleteNotifierConnection = `-- name: DeleteNotifierConnection :exec
DELETE FROM notifier_connection
WHERE cw_board_id = $1 AND webex_room_id = $2
`

type DeleteNotifierConnectionParams struct {
	CwBoardID   int `json:"cw_board_id"`
	WebexRoomID int `json:"webex_room_id"`
}

func (q *Queries) DeleteNotifierConnection(ctx context.Context, arg DeleteNotifierConnectionParams) error {
	_, err := q.db.Exec(ctx, deleteNotifierConnection, arg.CwBoardID, arg.WebexRoomID)
	return err
}

const insertNotifierConnection = `-- name: InsertNotifierConnection :one
INSERT INTO notifier_connection(cw_board_id, webex_room_id)
VALUES ($1, $2)
RETURNING cw_board_id, webex_room_id, notify_enabled, created_on
`

type InsertNotifierConnectionParams struct {
	CwBoardID   int `json:"cw_board_id"`
	WebexRoomID int `json:"webex_room_id"`
}

func (q *Queries) InsertNotifierConnection(ctx context.Context, arg InsertNotifierConnectionParams) (NotifierConnection, error) {
	row := q.db.QueryRow(ctx, insertNotifierConnection, arg.CwBoardID, arg.WebexRoomID)
	var i NotifierConnection
	err := row.Scan(
		&i.CwBoardID,
		&i.WebexRoomID,
		&i.NotifyEnabled,
		&i.CreatedOn,
	)
	return i, err
}

const listBoardsByRoom = `-- name: ListBoardsByRoom :many
SELECT b.id, b.name, b.updated_on, b.added_on, b.deleted FROM cw_board b
                    JOIN notifier_connection nc ON nc.cw_board_id = b.id
WHERE nc.webex_room_id = $1
`

func (q *Queries) ListBoardsByRoom(ctx context.Context, webexRoomID int) ([]CwBoard, error) {
	rows, err := q.db.Query(ctx, listBoardsByRoom, webexRoomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CwBoard
	for rows.Next() {
		var i CwBoard
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UpdatedOn,
			&i.AddedOn,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifierConnections = `-- name: ListNotifierConnections :many
SELECT cw_board_id, webex_room_id, notify_enabled, created_on FROM notifier_connection
ORDER BY cw_board_id
`

func (q *Queries) ListNotifierConnections(ctx context.Context) ([]NotifierConnection, error) {
	rows, err := q.db.Query(ctx, listNotifierConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotifierConnection
	for rows.Next() {
		var i NotifierConnection
		if err := rows.Scan(
			&i.CwBoardID,
			&i.WebexRoomID,
			&i.NotifyEnabled,
			&i.CreatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomsByBoard = `-- name: ListRoomsByBoard :many
SELECT w.id, w.webex_id, w.name, w.type, w.created_on, w.updated_on, w.deleted FROM webex_room w
                    JOIN notifier_connection nc ON nc.webex_room_id = w.id
WHERE nc.cw_board_id = $1 AND nc.notify_enabled = TRUE
`

func (q *Queries) ListRoomsByBoard(ctx context.Context, cwBoardID int) ([]WebexRoom, error) {
	rows, err := q.db.Query(ctx, listRoomsByBoard, cwBoardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebexRoom
	for rows.Next() {
		var i WebexRoom
		if err := rows.Scan(
			&i.ID,
			&i.WebexID,
			&i.Name,
			&i.Type,
			&i.CreatedOn,
			&i.UpdatedOn,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteNotifierConnection = `-- name: SoftDeleteNotifierConnection :exec
UPDATE notifier_connection
SET
    deleted = TRUE,
    updated_on = NOW()
WHERE cw_board_id = $1 AND webex_room_id = $2
`

type SoftDeleteNotifierConnectionParams struct {
	CwBoardID   int `json:"cw_board_id"`
	WebexRoomID int `json:"webex_room_id"`
}

func (q *Queries) SoftDeleteNotifierConnection(ctx context.Context, arg SoftDeleteNotifierConnectionParams) error {
	_, err := q.db.Exec(ctx, softDeleteNotifierConnection, arg.CwBoardID, arg.WebexRoomID)
	return err
}

const updateNotifierConnection = `-- name: UpdateNotifierConnection :one
UPDATE notifier_connection
SET notify_enabled = $3
WHERE cw_board_id = $1 AND webex_room_id = $2
RETURNING cw_board_id, webex_room_id, notify_enabled, created_on
`

type UpdateNotifierConnectionParams struct {
	CwBoardID     int  `json:"cw_board_id"`
	WebexRoomID   int  `json:"webex_room_id"`
	NotifyEnabled bool `json:"notify_enabled"`
}

func (q *Queries) UpdateNotifierConnection(ctx context.Context, arg UpdateNotifierConnectionParams) (NotifierConnection, error) {
	row := q.db.QueryRow(ctx, updateNotifierConnection, arg.CwBoardID, arg.WebexRoomID, arg.NotifyEnabled)
	var i NotifierConnection
	err := row.Scan(
		&i.CwBoardID,
		&i.WebexRoomID,
		&i.NotifyEnabled,
		&i.CreatedOn,
	)
	return i, err
}
