// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webex_room.sql

package db

import (
	"context"
)

const deleteWebexRoom = `-- name: DeleteWebexRoom :exec
DELETE FROM webex_room
WHERE id = $1
`

func (q *Queries) DeleteWebexRoom(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteWebexRoom, id)
	return err
}

const getWebexRoom = `-- name: GetWebexRoom :one
SELECT id, webex_id, name, type, created_on, updated_on, deleted FROM webex_room
WHERE id = $1
`

func (q *Queries) GetWebexRoom(ctx context.Context, id int) (WebexRoom, error) {
	row := q.db.QueryRow(ctx, getWebexRoom, id)
	var i WebexRoom
	err := row.Scan(
		&i.ID,
		&i.WebexID,
		&i.Name,
		&i.Type,
		&i.CreatedOn,
		&i.UpdatedOn,
		&i.Deleted,
	)
	return i, err
}

const getWebexRoomByWebexID = `-- name: GetWebexRoomByWebexID :one
SELECT id, webex_id, name, type, created_on, updated_on, deleted FROM webex_room
WHERE webex_id = $1
`

func (q *Queries) GetWebexRoomByWebexID(ctx context.Context, webexID string) (WebexRoom, error) {
	row := q.db.QueryRow(ctx, getWebexRoomByWebexID, webexID)
	var i WebexRoom
	err := row.Scan(
		&i.ID,
		&i.WebexID,
		&i.Name,
		&i.Type,
		&i.CreatedOn,
		&i.UpdatedOn,
		&i.Deleted,
	)
	return i, err
}

const getWebexRoomIDByInternalID = `-- name: GetWebexRoomIDByInternalID :one
SELECT webex_id FROM webex_room
WHERE id = $1
`

func (q *Queries) GetWebexRoomIDByInternalID(ctx context.Context, id int) (string, error) {
	row := q.db.QueryRow(ctx, getWebexRoomIDByInternalID, id)
	var webex_id string
	err := row.Scan(&webex_id)
	return webex_id, err
}

const insertWebexRoom = `-- name: InsertWebexRoom :one
INSERT INTO webex_room
(webex_id, name, type)
VALUES ($1, $2, $3)
RETURNING id, webex_id, name, type, created_on, updated_on, deleted
`

type InsertWebexRoomParams struct {
	WebexID string `json:"webex_id"`
	Name    string `json:"name"`
	Type    string `json:"type"`
}

func (q *Queries) InsertWebexRoom(ctx context.Context, arg InsertWebexRoomParams) (WebexRoom, error) {
	row := q.db.QueryRow(ctx, insertWebexRoom, arg.WebexID, arg.Name, arg.Type)
	var i WebexRoom
	err := row.Scan(
		&i.ID,
		&i.WebexID,
		&i.Name,
		&i.Type,
		&i.CreatedOn,
		&i.UpdatedOn,
		&i.Deleted,
	)
	return i, err
}

const listWebexRooms = `-- name: ListWebexRooms :many
SELECT id, webex_id, name, type, created_on, updated_on, deleted FROM webex_room
ORDER BY id
`

func (q *Queries) ListWebexRooms(ctx context.Context) ([]WebexRoom, error) {
	rows, err := q.db.Query(ctx, listWebexRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebexRoom
	for rows.Next() {
		var i WebexRoom
		if err := rows.Scan(
			&i.ID,
			&i.WebexID,
			&i.Name,
			&i.Type,
			&i.CreatedOn,
			&i.UpdatedOn,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteWebexRoom = `-- name: SoftDeleteWebexRoom :exec
UPDATE cw_board
SET
    deleted = TRUE,
    updated_on = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteWebexRoom(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, softDeleteWebexRoom, id)
	return err
}

const updateWebexRoom = `-- name: UpdateWebexRoom :one
UPDATE webex_room
SET
    name = $2,
    type = $3,
    updated_on = NOW()
WHERE id = $1
RETURNING id, webex_id, name, type, created_on, updated_on, deleted
`

type UpdateWebexRoomParams struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
	Type string `json:"type"`
}

func (q *Queries) UpdateWebexRoom(ctx context.Context, arg UpdateWebexRoomParams) (WebexRoom, error) {
	row := q.db.QueryRow(ctx, updateWebexRoom, arg.ID, arg.Name, arg.Type)
	var i WebexRoom
	err := row.Scan(
		&i.ID,
		&i.WebexID,
		&i.Name,
		&i.Type,
		&i.CreatedOn,
		&i.UpdatedOn,
		&i.Deleted,
	)
	return i, err
}
