// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webex_forwards.sql

package db

import (
	"context"
	"time"
)

const deleteWebexForward = `-- name: DeleteWebexForward :exec
DELETE FROM webex_user_forward
WHERE id = $1
`

func (q *Queries) DeleteWebexForward(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteWebexForward, id)
	return err
}

const getWebexUserForward = `-- name: GetWebexUserForward :one
SELECT wf.id, wf.user_email, wf.dest_room_id, wf.start_date, wf.end_date, wf.enabled, wf.user_keeps_copy, wf.created_on, wf.updated_on, wr.id, wr.webex_id, wr.name, wr.type, wr.created_on, wr.updated_on, wr.deleted
FROM webex_user_forward wf
JOIN webex_room AS wr ON wr.id = wf.source_room_id
WHERE wf.id = $1
`

type GetWebexUserForwardRow struct {
	WebexUserForward WebexUserForward `json:"webex_user_forward"`
	WebexRoom        WebexRoom        `json:"webex_room"`
}

func (q *Queries) GetWebexUserForward(ctx context.Context, id int) (GetWebexUserForwardRow, error) {
	row := q.db.QueryRow(ctx, getWebexUserForward, id)
	var i GetWebexUserForwardRow
	err := row.Scan(
		&i.WebexUserForward.ID,
		&i.WebexUserForward.UserEmail,
		&i.WebexUserForward.DestRoomID,
		&i.WebexUserForward.StartDate,
		&i.WebexUserForward.EndDate,
		&i.WebexUserForward.Enabled,
		&i.WebexUserForward.UserKeepsCopy,
		&i.WebexUserForward.CreatedOn,
		&i.WebexUserForward.UpdatedOn,
		&i.WebexRoom.ID,
		&i.WebexRoom.WebexID,
		&i.WebexRoom.Name,
		&i.WebexRoom.Type,
		&i.WebexRoom.CreatedOn,
		&i.WebexRoom.UpdatedOn,
		&i.WebexRoom.Deleted,
	)
	return i, err
}

const insertWebexUserForward = `-- name: InsertWebexUserForward :one
INSERT INTO webex_user_forward (
    user_email, dest_room_id, start_date, end_date, enabled, user_keeps_copy
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_email, dest_room_id, start_date, end_date, enabled, user_keeps_copy, created_on, updated_on
`

type InsertWebexUserForwardParams struct {
	UserEmail     string     `json:"user_email"`
	DestRoomID    int        `json:"dest_room_id"`
	StartDate     *time.Time `json:"start_date"`
	EndDate       *time.Time `json:"end_date"`
	Enabled       bool       `json:"enabled"`
	UserKeepsCopy bool       `json:"user_keeps_copy"`
}

func (q *Queries) InsertWebexUserForward(ctx context.Context, arg InsertWebexUserForwardParams) (WebexUserForward, error) {
	row := q.db.QueryRow(ctx, insertWebexUserForward,
		arg.UserEmail,
		arg.DestRoomID,
		arg.StartDate,
		arg.EndDate,
		arg.Enabled,
		arg.UserKeepsCopy,
	)
	var i WebexUserForward
	err := row.Scan(
		&i.ID,
		&i.UserEmail,
		&i.DestRoomID,
		&i.StartDate,
		&i.EndDate,
		&i.Enabled,
		&i.UserKeepsCopy,
		&i.CreatedOn,
		&i.UpdatedOn,
	)
	return i, err
}

const listWebexUserForwards = `-- name: ListWebexUserForwards :many
SELECT wf.id, wf.user_email, wf.dest_room_id, wf.start_date, wf.end_date, wf.enabled, wf.user_keeps_copy, wf.created_on, wf.updated_on, wr.id, wr.webex_id, wr.name, wr.type, wr.created_on, wr.updated_on, wr.deleted
FROM webex_user_forward wf
JOIN webex_room AS wr ON wr.id = wf.dest_room_id
WHERE ($1::text IS NULL OR wf.email = $1)
`

type ListWebexUserForwardsRow struct {
	WebexUserForward WebexUserForward `json:"webex_user_forward"`
	WebexRoom        WebexRoom        `json:"webex_room"`
}

func (q *Queries) ListWebexUserForwards(ctx context.Context, email *string) ([]ListWebexUserForwardsRow, error) {
	rows, err := q.db.Query(ctx, listWebexUserForwards, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWebexUserForwardsRow
	for rows.Next() {
		var i ListWebexUserForwardsRow
		if err := rows.Scan(
			&i.WebexUserForward.ID,
			&i.WebexUserForward.UserEmail,
			&i.WebexUserForward.DestRoomID,
			&i.WebexUserForward.StartDate,
			&i.WebexUserForward.EndDate,
			&i.WebexUserForward.Enabled,
			&i.WebexUserForward.UserKeepsCopy,
			&i.WebexUserForward.CreatedOn,
			&i.WebexUserForward.UpdatedOn,
			&i.WebexRoom.ID,
			&i.WebexRoom.WebexID,
			&i.WebexRoom.Name,
			&i.WebexRoom.Type,
			&i.WebexRoom.CreatedOn,
			&i.WebexRoom.UpdatedOn,
			&i.WebexRoom.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
