// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webex_forwards.sql

package db

import (
	"context"
	"time"
)

const deleteWebexForward = `-- name: DeleteWebexForward :exec
DELETE FROM webex_user_forward
WHERE id = $1
`

func (q *Queries) DeleteWebexForward(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteWebexForward, id)
	return err
}

const getWebexUserForward = `-- name: GetWebexUserForward :one
SELECT id, source_room_id, dest_room_id, start_date, end_date, enabled, user_keeps_copy, created_on, updated_on FROM webex_user_forward
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetWebexUserForward(ctx context.Context, id int) (WebexUserForward, error) {
	row := q.db.QueryRow(ctx, getWebexUserForward, id)
	var i WebexUserForward
	err := row.Scan(
		&i.ID,
		&i.SourceRoomID,
		&i.DestRoomID,
		&i.StartDate,
		&i.EndDate,
		&i.Enabled,
		&i.UserKeepsCopy,
		&i.CreatedOn,
		&i.UpdatedOn,
	)
	return i, err
}

const insertWebexUserForward = `-- name: InsertWebexUserForward :one
INSERT INTO webex_user_forward (
    source_room_id, dest_room_id, start_date, end_date, enabled, user_keeps_copy
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, source_room_id, dest_room_id, start_date, end_date, enabled, user_keeps_copy, created_on, updated_on
`

type InsertWebexUserForwardParams struct {
	SourceRoomID  int        `json:"source_room_id"`
	DestRoomID    int        `json:"dest_room_id"`
	StartDate     *time.Time `json:"start_date"`
	EndDate       *time.Time `json:"end_date"`
	Enabled       bool       `json:"enabled"`
	UserKeepsCopy bool       `json:"user_keeps_copy"`
}

func (q *Queries) InsertWebexUserForward(ctx context.Context, arg InsertWebexUserForwardParams) (WebexUserForward, error) {
	row := q.db.QueryRow(ctx, insertWebexUserForward,
		arg.SourceRoomID,
		arg.DestRoomID,
		arg.StartDate,
		arg.EndDate,
		arg.Enabled,
		arg.UserKeepsCopy,
	)
	var i WebexUserForward
	err := row.Scan(
		&i.ID,
		&i.SourceRoomID,
		&i.DestRoomID,
		&i.StartDate,
		&i.EndDate,
		&i.Enabled,
		&i.UserKeepsCopy,
		&i.CreatedOn,
		&i.UpdatedOn,
	)
	return i, err
}

const listWebexUserForwards = `-- name: ListWebexUserForwards :many
SELECT id, source_room_id, dest_room_id, start_date, end_date, enabled, user_keeps_copy, created_on, updated_on FROM webex_user_forward
ORDER BY id
`

func (q *Queries) ListWebexUserForwards(ctx context.Context) ([]WebexUserForward, error) {
	rows, err := q.db.Query(ctx, listWebexUserForwards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebexUserForward
	for rows.Next() {
		var i WebexUserForward
		if err := rows.Scan(
			&i.ID,
			&i.SourceRoomID,
			&i.DestRoomID,
			&i.StartDate,
			&i.EndDate,
			&i.Enabled,
			&i.UserKeepsCopy,
			&i.CreatedOn,
			&i.UpdatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebexUserForwardsBySourceRoomID = `-- name: ListWebexUserForwardsBySourceRoomID :many
SELECT id, source_room_id, dest_room_id, start_date, end_date, enabled, user_keeps_copy, created_on, updated_on FROM webex_user_forward
WHERE source_room_id = $1
ORDER BY id
`

func (q *Queries) ListWebexUserForwardsBySourceRoomID(ctx context.Context, sourceRoomID int) ([]WebexUserForward, error) {
	rows, err := q.db.Query(ctx, listWebexUserForwardsBySourceRoomID, sourceRoomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebexUserForward
	for rows.Next() {
		var i WebexUserForward
		if err := rows.Scan(
			&i.ID,
			&i.SourceRoomID,
			&i.DestRoomID,
			&i.StartDate,
			&i.EndDate,
			&i.Enabled,
			&i.UserKeepsCopy,
			&i.CreatedOn,
			&i.UpdatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
